# Check our guides at https://confluence.atlassian.com/x/VYk8Lw for more examples.
image: python:2.7

pipelines:
  custom:
    deploy-dev:
      - step:
          script:
            - export CLOUDSDK_CORE_DISABLE_PROMPTS=1
            - curl -sSL https://sdk.cloud.google.com | bash
            - export PATH=${PATH}:${HOME}/google-cloud-sdk/bin

            # Auth gcloud
            - echo ${JSON_SECRET_SC_DEV} > client-secret.json
            - gcloud config set project ${PROJECT_KEY_SC_DEV};
            - gcloud auth activate-service-account --key-file client-secret.json

            # Prepare app
            - npm install
            - npm run compile
            - npm run typings
            - npm run bundle:prod
            - unlink public/index.html; mv public/index-prod.html public/index.html

            # Deploy app
            - gcloud app deploy

    deploy-qa:
      - step:
          script:
            - export CLOUDSDK_CORE_DISABLE_PROMPTS=1
            - curl -sSL https://sdk.cloud.google.com | bash
            - export PATH=${PATH}:${HOME}/google-cloud-sdk/bin

            # Auth gcloud
            - echo ${JSON_SECRET_SC_QA} > client-secret.json
            - gcloud config set project ${PROJECT_KEY_SC_QA};
            - gcloud auth activate-service-account --key-file client-secret.json

            # Prepare app
            - npm install
            - npm run compile
            - npm run typings
            - npm run bundle:prod
            - unlink public/index.html; mv public/index-prod.html public/index.html

            # Deploy app
            - gcloud app deploy
